# Generated by Django 4.0 on 2022-01-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_person_article_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cat',
        ),
    ]
