# Generated by Django 4.0 on 2022-01-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_thumb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
